
season: 47
cost_per_day: 1
sole_survivor_bonus: 5

picks:
    tom: rome
    kelsey: teeny
    eric: tiyana
    alana: caroline
    janice: sol
    paty: rachel
    john: sierra
    kathy: kishan
    kelly: sue
    mary: genevieve
    chelsea: aysha

castaways:
    jon:
        full_name: Jon Lovett
        finish:
            day: 3
    andy:
        full_name: Andy Rueda
        finish:
            day: null
    anika:
        full_name: Anika Dhar
        finish:
            day: null
    aysha:
        full_name: Aysha Welch
        finish:
            day: null
    caroline:
        full_name: Caroline Vidmar
        finish:
            day: null
    teeny:
        full_name: Christine "Teeny" Chirichillo
        finish:
            day: null
    gabe:
        full_name: Gabe Ortis
        finish:
            day: null
    genevieve:
        full_name: Genevieve Mushaluk
        finish:
            day: null
    rome:
        full_name: Jerome "Rome" Cooney
        finish:
            day: null
    kishan:
        full_name: Kishan Patel
        finish:
            day: null
    kyle:
        full_name: Kyle Ostwald
        finish:
            day: null
    rachel:
        full_name: Rachel LaMont
        finish:
            day: null
    sam:
        full_name: Sam Phalen
        finish:
            day: null
    sierra:
        full_name: Sierra Wright
        finish:
            day: null
    sol:
        full_name: Solomon "Sol" Yi
        finish:
            day: null
    sue:
        full_name: Sue Smey
        finish:
            day: null
    tk:
        full_name: Terran "TK" Foster
        finish:
            day: 5
    tiyana:
        full_name: Tiyana Hallums
        finish:
            day: null
