
people:
    eric:
        first: Eric
        last: Lamphere
    kelly:
        first: Kelly
        last: Medeiros
    janice:
        first: Janice
        last: Lamphere
    kelsey:
        first: Kelsey
        last: Lamphere
    kathy:
        first: Kathy
        last: Bowie
    mary:
        first: Mary
        last: Medeiros
    john:
        first: John
        last: Medeiros
    paty:
        first: Paty
        last: Martin
    alana:
        first: Alana
        last: Medeiros
    tom:
        first: Tom
        last: Mcguinness
    chelsea:
        first: Chelsea
        last: Harshbarger
