
season: 46

picks:
    kathy: maria
    john: venus
    paty: tevin
    janice: soda
    kelsey: jem
    eric: moriah
    kelly: kenzie
    tom: bhanu
    alana: tim

castaways:
    jelinsky:
        full_name: David Jelinsky
        finish:
            day: 3
    jess:
        full_name: Jessica "Jess" Chong
        finish:
            day: 5
    randen:
        full_name: Randen Montalvo
        finish:
            day: 7
    bhanu:
        full_name: Bhanu Gopal
        finish:
            day: 9
    jem:
        full_name: Jemila "Jem" Hussain-Adams
        finish:
            day: 11
    moriah:
        full_name: Moriah Gaynor
        finish:
            day: 13
    tim:
        full_name: Tim Spicer
        finish:
            day: 14
            tie_breaker: 2
    soda:
        full_name: Sodasia "Soda" Thompson
        finish:
            day: 14
            tie_breaker: 1
    tevin:
        full_name: Tevin Davis
        finish:
            day: 16
    hunter:
        full_name: Hunter McKnight
        finish:
            day: 17
    tiffany:
        full_name: Tiffany Nicole Ervin
        finish:
            day: 19
    venus:
        full_name: Venus Vafa
        finish:
            day: 21
    q:
        full_name: Quintavius "Q" Burdette
        finish:
            day: 23
    maria:
        full_name: Maria Shrime Gonzalez
        finish:
            day: 24
    liz:
        full_name: Liz Wilcox
        finish:
            day: 25
    ben:
        full_name: Ben Katzman
        finish:
            day: 26
            tie_breaker: 3
    charlie:
        full_name: Charlie Davis
        finish:
            day: 26
            tie_breaker: 2
    kenzie:
        full_name: Kenzie Petty
        finish:
            day: 26
            tie_breaker: 1

