# name: Deploy to shinyapps.io
# on:
#   workflow_dispatch:
#       
# jobs:
#   deploy:
#     name: Deploy App
# 
#     # allow skipping deployment for commits containing '[automated]' or '[no-deploy]' in the commit message
#     if: "!contains(github.event.head_commit.message, '[automated]') && !contains(github.event.head_commit.message, '[no-deploy]')"
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: deploy
#         uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
#         with:
#           # account and application name (https://<accountName>.shinyapps.io/<appName>)
#           appName: survivor-dev
#           accountName: ${{ vars.SHINYAPPS_ACCOUNT_NAME }}
# 
#           # token and secret obtained from https://www.shinyapps.io/admin/#/tokens
#           accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
#           accountSecret: ${{ secrets.SHINYAPPS_SECRET }}
          
on: [push]

name: Deploy App

jobs:
    deploy:
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v2
            - uses: r-lib/actions/setup-r@v2
            - name: Install Packages
              env:
                GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
              run: | 
                Rscript -e "install.packages(c('shiny', 'rsconnect', 'renv'), type = 'binary')"
                Rscript -e "renv::consent(provided = FALSE); renv::restore()"
            - name: Push to shiny.io
              env: 
                SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
                SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
                SHINYAPPS_ACCOUNT_NAME: ${{ vars.SHINYAPPS_ACCOUNT_NAME }}
                APP_NAME: survivor
              run: |
                Rscript -e "rsconnect::setAccountInfo(name=Sys.getenv('SHINYAPPS_ACCOUNT_NAME'), token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))" 
                Rscript -e "rsconnect::deployApp(appDir = './', appName = Sys.getenv('APP_NAME'))"
  
  
  
  