
          
on: 
    push:
        branches:
            - main

name: Deploy App

env:
    APP_NAME: survivor_dev

jobs:
    deploy:
        runs-on: macOS-14
        steps:
            - uses: actions/checkout@v2
            - uses: r-lib/actions/setup-r@v2
              with:
                r-version: '4.4.1'
            
            - name: Install Packages
              env:
                GITHUB_PAT: ${{ secrets.GH_READ_TOKEN }}
              run: | 
                Rscript -e "install.packages(c('shiny', 'rsconnect', 'renv'), type = 'binary')"
                Rscript -e "renv::consent(provided = FALSE); renv::restore()"
            
            - name: Create Google Service Account Key File
              env: |
                GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
              run: |
                mkdir .secrets && echo "$GCP_SERVICE_ACCOUNT_KEY" > .secrets/gcp-service-account.json
            
            - name: Authenticate Google Sheets
              run: |
                Rscript -e 'googlesheets4::gs4_auth(path = ".secrets/gcp-service-account.json")'
            
            - name: Push to shiny.io
              env: 
                SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
                SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
                SHINYAPPS_ACCOUNT_NAME: ${{ vars.SHINYAPPS_ACCOUNT_NAME }}
              run: |
                Rscript -e "rsconnect::setAccountInfo(
                    name=Sys.getenv('SHINYAPPS_ACCOUNT_NAME'), 
                    token=Sys.getenv('SHINYAPPS_TOKEN'), 
                    secret=Sys.getenv('SHINYAPPS_SECRET')
                )" 
                Rscript -e "rsconnect::deployApp(appDir = './', appName = Sys.getenv('APP_NAME'), forceUpdate = TRUE)"
  
  
  
  